version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - PGDATA=/var/lib/postgres/data/pgdata
      - POSTGRES_DB=blogs_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgres/data/pgdata
    networks:
      - blogs
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@namsu.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin1234
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - blogs
networks:
  blogs:
    name: blogs
volumes:
  pgdata:
  pgadmin:
